version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

loggers:
  all:
    handlers: [all]
    propagate: false
  tornado:
    handlers: [all ,console]
    propagate: false

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  all:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    when: midnight
    filename: ./logs/app.log

root:
  level: INFO
  handlers: [console, all]
  propagate: true
